server:
  port: 8081
  ssl:
    key-store-password: 64cnb35z87p4306    #填写jks-password.txt文件内的密码。
    key-store-type: JKS #JKS格式证书密钥库类型。PFX格式的证书密钥库类型为PKCS12。
    key-store: classpath:organwalk.ink.jks   #您需要使用实际的证书名称替换domain_name.jks。
spring:
  # MySQL数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false
    username: root
    password: 123456
  transaction:
    default-timeout: 10